# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# --------------------------------------------------------------------------

"""
Service registry containing metadata for all Azure Management services.

This registry maps ServiceType enums to their corresponding:
- Azure Resource Provider names (Microsoft.*)
- Python package names (azure.mgmt.*)
- Default API versions
- Operation group names
"""

from typing import Dict, List, Any
from ._enums import ServiceType


# Service metadata registry
SERVICE_REGISTRY: Dict[ServiceType, Dict[str, Any]] = {
    ServiceType.ADVISOR: {
        "resource_provider": "Microsoft.Advisor",
        "package": "azure.mgmt.advisor",
        "client_class": "AdvisorManagementClient",
        "default_api_version": "2020-01-01",
        "operations": [
            "configurations",
            "operations",
            "recommendation_metadata",
            "recommendations",
            "suppressions",
        ],
    },
    ServiceType.STORAGE: {
        "resource_provider": "Microsoft.Storage",
        "package": "azure.mgmt.storage",
        "client_class": "StorageManagementClient",
        "default_api_version": "2023-05-01",
        "operations": [
            "blob_containers",
            "blob_services",
            "encryption_scopes",
            "file_services",
            "file_shares",
            "management_policies",
            "object_replication_policies",
            "operations",
            "private_endpoint_connections",
            "private_link_resources",
            "queue",
            "queue_services",
            "skus",
            "storage_accounts",
            "table",
            "table_services",
            "usages",
        ],
    },
    ServiceType.COMPUTE: {
        "resource_provider": "Microsoft.Compute",
        "package": "azure.mgmt.compute",
        "client_class": "ComputeManagementClient",
        "default_api_version": "2024-07-01",
        "operations": [
            "availability_sets",
            "capacity_reservation_groups",
            "capacity_reservations",
            "cloud_service_role_instances",
            "cloud_service_roles",
            "cloud_services",
            "cloud_services_update_domain",
            "community_galleries",
            "community_gallery_images",
            "community_gallery_image_versions",
            "dedicated_host_groups",
            "dedicated_hosts",
            "disk_accesses",
            "disk_encryption_sets",
            "disk_restore_point",
            "disks",
            "galleries",
            "gallery_applications",
            "gallery_application_versions",
            "gallery_images",
            "gallery_image_versions",
            "gallery_sharing_profile",
            "images",
            "log_analytics",
            "operations",
            "proximity_placement_groups",
            "resource_skus",
            "restore_point_collections",
            "restore_points",
            "shared_galleries",
            "shared_gallery_images",
            "shared_gallery_image_versions",
            "snapshots",
            "ssh_public_keys",
            "usages",
            "virtual_machine_extension_images",
            "virtual_machine_extensions",
            "virtual_machine_images",
            "virtual_machine_images_edge_zone",
            "virtual_machine_run_commands",
            "virtual_machines",
            "virtual_machine_scale_set_extensions",
            "virtual_machine_scale_set_rolling_upgrades",
            "virtual_machine_scale_sets",
            "virtual_machine_scale_set_vm_extensions",
            "virtual_machine_scale_set_vms",
            "virtual_machine_sizes",
        ],
    },
    ServiceType.NETWORK: {
        "resource_provider": "Microsoft.Network",
        "package": "azure.mgmt.network",
        "client_class": "NetworkManagementClient",
        "default_api_version": "2024-01-01",
        "operations": [
            "application_gateways",
            "application_gateway_private_endpoint_connections",
            "application_gateway_private_link_resources",
            "application_gateway_waf_dynamic_manifests_default",
            "application_gateway_waf_dynamic_manifests",
            "application_security_groups",
            "available_delegations",
            "available_endpoint_services",
            "available_private_endpoint_types",
            "available_resource_group_delegations",
            "available_service_aliases",
            "azure_firewall_fqdn_tags",
            "azure_firewalls",
            "bastion_hosts",
            "bgp_service_communities",
            "connection_monitors",
            "custom_ip_prefixes",
            "ddos_custom_policies",
            "ddos_protection_plans",
            "default_security_rules",
            "dscp_configuration",
            "express_route_circuit_authorizations",
            "express_route_circuit_connections",
            "express_route_circuit_peerings",
            "express_route_circuits",
            "express_route_connections",
            "express_route_cross_connection_peerings",
            "express_route_cross_connections",
            "express_route_gateways",
            "express_route_links",
            "express_route_port_authorizations",
            "express_route_ports_locations",
            "express_route_ports",
            "express_route_provider_ports_location",
            "express_route_service_providers",
            "firewall_policies",
            "firewall_policy_idps_signatures",
            "firewall_policy_idps_signatures_filter_values",
            "firewall_policy_idps_signatures_overrides",
            "firewall_policy_rule_collection_groups",
            "flow_logs",
            "hub_route_tables",
            "hub_virtual_network_connections",
            "inbound_nat_rules",
            "inbound_security_rule",
            "ip_allocations",
            "ip_groups",
            "load_balancer_backend_address_pools",
            "load_balancer_frontend_ip_configurations",
            "load_balancer_load_balancing_rules",
            "load_balancer_network_interfaces",
            "load_balancer_outbound_rules",
            "load_balancer_probes",
            "load_balancers",
            "local_network_gateways",
            "management_group_network_manager_connections",
            "nat_gateways",
            "nat_rules",
            "network_groups",
            "network_interface_ip_configurations",
            "network_interface_load_balancers",
            "network_interfaces",
            "network_interface_tap_configurations",
            "network_manager_commits",
            "network_manager_deployment_status",
            "network_managers",
            "network_profiles",
            "network_security_groups",
            "network_security_perimeters",
            "network_virtual_appliances",
            "network_watcher_connection_monitors",
            "network_watchers",
            "operations",
            "p2s_vpn_gateways",
            "packet_captures",
            "peer_express_route_circuit_connections",
            "private_dns_zone_groups",
            "private_endpoints",
            "private_link_services",
            "public_ip_addresses",
            "public_ip_prefixes",
            "resource_navigation_links",
            "route_filters",
            "route_filter_rules",
            "routes",
            "route_tables",
            "scope_connections",
            "security_admin_configurations",
            "security_partner_providers",
            "security_rules",
            "security_user_configurations",
            "service_association_links",
            "service_endpoint_policies",
            "service_endpoint_policy_definitions",
            "service_tags",
            "static_members",
            "subnets",
            "subscription_network_manager_connections",
            "usages",
            "virtual_appliance_sites",
            "virtual_appliance_skus",
            "virtual_hubs",
            "virtual_hub_bgp_connection",
            "virtual_hub_bgp_connections",
            "virtual_hub_ip_configuration",
            "virtual_hub_route_table_v2s",
            "virtual_network_gateway_connections",
            "virtual_network_gateway_nat_rules",
            "virtual_network_gateways",
            "virtual_networks",
            "virtual_network_peerings",
            "virtual_network_taps",
            "virtual_router_peerings",
            "virtual_routers",
            "virtual_wans",
            "vpn_connections",
            "vpn_gateways",
            "vpn_link_connections",
            "vpn_server_configurations",
            "vpn_server_configurations_associated_with_virtual_wan",
            "vpn_site_link_connections",
            "vpn_site_links",
            "vpn_sites",
            "web_application_firewall_policies",
            "web_categories",
        ],
    },
    ServiceType.API_MANAGEMENT: {
        "resource_provider": "Microsoft.ApiManagement",
        "package": "azure.mgmt.apimanagement",
        "client_class": "ApiManagementClient",
        "default_api_version": "2022-08-01",
        "operations": [
            "api",
            "api_diagnostic",
            "api_export",
            "api_gateway",
            "api_gateway_config_connection",
            "api_issue",
            "api_issue_attachment",
            "api_issue_comment",
            "api_management_operations",
            "api_management_service",
            "api_management_service_skus",
            "api_management_sku",
            "api_operation",
            "api_operation_policy",
            "api_policy",
            "api_product",
            "api_release",
            "api_revision",
            "api_schema",
            "api_tag_description",
            "api_version_set",
            "api_wiki",
            "api_wikis",
            "authorization",
            "authorization_access_policy",
            "authorization_login_links",
            "authorization_provider",
            "authorization_server",
            "backend",
            "cache",
            "certificate",
            "content_item",
            "content_type",
            "delegated_subscription_or_group",
            "delegation_settings",
            "deleted_services",
            "diagnostic",
            "documentation",
            "email_template",
            "gateway",
            "gateway_api",
            "gateway_certificate_authority",
            "gateway_hostname_configuration",
            "global_schema",
            "graph_ql_api_resolver",
            "graph_ql_api_resolver_policy",
            "group",
            "group_user",
            "identity_provider",
            "issue",
            "logger",
            "named_value",
            "network_status",
            "notification",
            "notification_recipient_email",
            "notification_recipient_user",
            "open_id_connect_provider",
            "operation",
            "outbound_network_dependencies_endpoints",
            "policy",
            "policy_description",
            "policy_fragment",
            "policy_restriction",
            "policy_restrictions_validations",
            "portal_config",
            "portal_revision",
            "portal_settings",
            "private_endpoint_connection",
            "product",
            "product_api",
            "product_group",
            "product_policy",
            "product_subscription",
            "product_wiki",
            "product_wikis",
            "quota_by_counter_keys",
            "quota_by_period_keys",
            "region",
            "reports",
            "sign_in_settings",
            "sign_up_settings",
            "subscription",
            "tag",
            "tag_resource",
            "tenant_access",
            "tenant_access_git",
            "tenant_configuration",
            "tenant_settings",
            "user",
            "user_confirmation_password",
            "user_group",
            "user_identities",
            "user_subscription",
            "workspace",
            "workspace_api",
            "workspace_api_operation",
            "workspace_api_operation_policy",
            "workspace_api_policy",
            "workspace_api_product",
            "workspace_api_release",
            "workspace_api_revision",
            "workspace_api_schema",
            "workspace_api_version_set",
            "workspace_group",
            "workspace_group_user",
            "workspace_named_value",
            "workspace_notification",
            "workspace_notification_recipient_email",
            "workspace_notification_recipient_user",
            "workspace_policy",
            "workspace_policy_fragment",
            "workspace_product",
            "workspace_product_api_link",
            "workspace_product_group",
            "workspace_product_policy",
            "workspace_subscription",
            "workspace_tag",
            "workspace_tag_api_link",
            "workspace_tag_operation_link",
            "workspace_tag_product_link",
        ],
    },
}


# Operation name to service mapping (for automatic service detection)
OPERATION_TO_SERVICE: Dict[str, ServiceType] = {}
for service, metadata in SERVICE_REGISTRY.items():
    for operation in metadata["operations"]:
        if operation not in OPERATION_TO_SERVICE:
            OPERATION_TO_SERVICE[operation] = service
        else:
            # Handle naming collisions - operations that exist in multiple services
            # For now, we'll need explicit service specification for these
            pass


def get_service_for_operation(operation_name: str) -> ServiceType:
    """Get the service type for a given operation name.
    
    Args:
        operation_name: The operation group name (e.g., 'storage_accounts')
        
    Returns:
        The ServiceType enum for this operation.
        
    Raises:
        KeyError: If the operation is not found or exists in multiple services.
    """
    if operation_name not in OPERATION_TO_SERVICE:
        raise KeyError(
            f"Operation '{operation_name}' not found in service registry. "
            "You may need to specify the service explicitly."
        )
    return OPERATION_TO_SERVICE[operation_name]


def get_service_metadata(service: ServiceType) -> Dict[str, Any]:
    """Get metadata for a service.
    
    Args:
        service: The ServiceType enum.
        
    Returns:
        Dictionary containing service metadata.
    """
    return SERVICE_REGISTRY[service]
