# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, TypeVar, Generic, Type, Union
from typing_extensions import TypedDict, Required, NotRequired
from azure.core import CaseInsensitiveEnumMeta


T = TypeVar("T")  # bound by model?
TResourceType = TypeVar('TResourceType', bound='ResourceType')

class ResourceTypeParameters(TypedDict):
    """Base parameters for all resource types."""
    resource_group_name: Required[str]
    api_version: NotRequired[str]
    properties: NotRequired[Optional[Any]]

class ResourceType(Generic[T]):
    """Common ARM resource fields."""
    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "properties": {"readonly": False}
    }

    # Default URL template - should be overridden by subclasses
    _url_template = (
        "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/"
        "providers/{resourceProvider}/{resourceType}/{resourceName}"
    )

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.resource_group_name: str
        self.resource_name: str
        self.id = None
        self.name = None
        self.type = None
        self.properties: Optional[T] = None

    @classmethod
    def get_url_template(cls) -> str:
        """Get the URL template for this resource type.

        :return: The URL template string
        :rtype: str
        """
        return cls._url_template

    @classmethod
    def from_response(
        cls: Type[TResourceType], data_dict: Dict[str, Any], **kwargs
    ) -> TResourceType:
        """Create instance from API response data and request parameters.

        :param cls: The resource type class
        :type cls: Type[TResourceType]
        :param data_dict: The response data dictionary from Azure API
        :type data_dict: Dict[str, Any]
        :return: Created instance of the resource type
        :rtype: TResourceType
        """
        properties = data_dict.get('properties', {})

        # Create instance with constructor parameters from kwargs
        instance = cls(**kwargs, properties=properties)

        # Set response data attributes
        instance.id = data_dict.get('id')
        instance.name = data_dict.get('name')
        instance.type = data_dict.get('type')

        return instance

    def build_instance_path_arguments(self, subscription_id: str) -> Dict[str, str]:
        """Build path arguments from instance attributes.

        :param subscription_id: The Azure subscription ID
        :type subscription_id: str
        :return: Dictionary of path arguments for URL construction
        :rtype: Dict[str, str]
        """
        return {
            "subscriptionId": subscription_id,
            "resourceGroupName": self.resource_group_name,
            "resourceName": self.resource_name,
        }


