# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import re
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional, TypeVar, Generic, Mapping, Type # pylint: disable=unused-import


PropertiesT = TypeVar("PropertiesT")
PathParamsT = TypeVar("PathParamsT")
TResourceType = TypeVar("TResourceType", bound="ResourceType[Any, Mapping[str, str]]")
TResourceId = TypeVar("TResourceId", bound="ResourceId[Any]")


class ResourceId(ABC, Generic[PathParamsT]):
    """Base class for resource identity and URL building.
    
    ResourceId encapsulates the identity information required to address
    a specific Azure resource instance (e.g., resource group, resource name).
    It handles URL template formatting and provides methods to parse ARM
    resource ID strings.
    """
    
    # URL templates - should be overridden by subclasses
    _url_template: str = ""
    _list_url_template: str = ""
    _action_url_templates: Dict[str, str] = {}
    
    @abstractmethod
    def to_dict(self) -> PathParamsT:
        """Convert this ResourceId to its PathParams TypedDict representation.
        
        :return: PathParams dictionary with all URL parameter values
        :rtype: PathParamsT
        """
        ...
    
    @classmethod
    @abstractmethod
    def from_dict(cls: Type[TResourceId], params: PathParamsT) -> TResourceId:
        """Create a ResourceId from a PathParams TypedDict.
        
        :param params: URL parameters dictionary
        :type params: PathParamsT
        :return: New ResourceId instance
        :rtype: TResourceId
        """
        ...
    
    @classmethod
    @abstractmethod
    def from_resource_id(cls: Type[TResourceId], resource_id: str) -> TResourceId:
        """Parse an ARM resource ID string and create a ResourceId.
        
        ARM resource IDs follow the pattern:
        /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{provider}/{type}/{name}
        
        :param resource_id: Full ARM resource ID string
        :type resource_id: str
        :return: New ResourceId instance
        :rtype: TResourceId
        :raises ValueError: If the resource ID format is invalid
        """
        ...
    
    @abstractmethod
    def build_path_arguments(self, subscription_id: str) -> Dict[str, Any]:
        """Build path arguments dictionary for URL formatting.
        
        :param subscription_id: Azure subscription ID
        :type subscription_id: str
        :return: Dictionary of path arguments for URL template formatting
        :rtype: Dict[str, Any]
        """
        ...
    
    @classmethod
    def get_operation_url(
        cls,
        operation: str,
        subscription_id: str,
        resource_id: "ResourceId[PathParamsT]",
    ) -> str:
        """Get the URL template for the given operation.
        
        :param operation: Operation name (e.g., "read", "create", "delete", "update", "list")
        :type operation: str
        :param subscription_id: Azure subscription ID
        :type subscription_id: str
        :param resource_id: ResourceId instance containing identity information
        :type resource_id: ResourceId[PathParamsT]
        :return: Formatted URL for the operation
        :rtype: str
        :raises ValueError: If operation is not supported
        """
        # Subclasses can override for operation-specific templates
        # Base implementation uses _url_template for all operations except list
        if operation == "list":
            return cls._list_url_template
        return cls._url_template
    
    @classmethod
    def get_action_url(
        cls,
        action: str,
        subscription_id: str,
        resource_id: "ResourceId[PathParamsT]",
    ) -> str:
        """Get the URL for a resource action (POST operation).
        
        :param action: The action name
        :type action: str
        :param subscription_id: Azure subscription ID
        :type subscription_id: str
        :param resource_id: ResourceId instance containing identity information
        :type resource_id: ResourceId[PathParamsT]
        :return: Formatted URL for the action
        :rtype: str
        :raises ValueError: If action is not supported
        """
        if action not in cls._action_url_templates:
            raise ValueError(
                f"Unsupported action '{action}' for {cls.__name__}. "
                f"Available actions: {list(cls._action_url_templates.keys())}"
            )
        return cls._action_url_templates[action]


class ResourceType(Generic[PropertiesT, PathParamsT]):
    """Common ARM resource fields.
    
    ResourceType represents the properties and response data of an Azure resource,
    separate from its identity information (which is handled by ResourceId).
    """
    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "properties": {"readonly": False}
    }

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        # ARM resource response fields (populated from API responses)
        self.id = None
        self.name = None
        self.type = None
        self.properties: Optional[PropertiesT] = None

    @classmethod
    def from_response(
        cls, data_dict: Dict[str, Any], **kwargs: Any
    ) -> "ResourceType":
        """Create instance from API response data and request parameters.

        :param cls: The resource type class
        :type cls: Type[TResourceType]
        :param data_dict: The response data dictionary from Azure API
        :type data_dict: Dict[str, Any]
        :return: Created instance of the resource type
        :rtype: TResourceType
        """
        properties = data_dict.get('properties', {})

        # Create instance with constructor parameters from kwargs
        instance = cls(**kwargs, properties=properties)

        # Set response data attributes
        instance.id = data_dict.get('id')
        instance.name = data_dict.get('name')
        instance.type = data_dict.get('type')

        return instance

    def to_dict(self) -> Dict[str, Any]:
        """Convert the resource to a dictionary for API requests.
        
        :return: Dictionary representation of the resource
        :rtype: Dict[str, Any]
        """
        return {
            "properties": self.properties,
        }
