# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, TypeVar, Generic, Type, Union, Mapping
from typing_extensions import TypedDict, Required, NotRequired
from azure.core import CaseInsensitiveEnumMeta


PropertiesT = TypeVar("PropertiesT")
PathParamsT = TypeVar("PathParamsT")
TResourceType = TypeVar("TResourceType", bound="ResourceType[Any, Mapping[str, str]]")


class ResourceType(Generic[PropertiesT, PathParamsT]):
    """Common ARM resource fields."""
    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "properties": {"readonly": False}
    }

    # Default URL template - should be overridden by subclasses
    _url_template = (
        "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/"
        "providers/{resourceProvider}/{resourceType}/{resourceName}"
    )

    _list_url_template = _url_template

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        # Common ARM identity fields
        self.resource_group_name: str = kwargs.get("resource_group_name", "")
        self.resource_name: str = kwargs.get("resource_name", "")
        self.id = None
        self.name = None
        self.type = None
        self.properties: Optional[PropertiesT] = None

    @classmethod
    def get_operation_url(
        cls,
        operation: str,
        subscription_id: str,
        url_params: PathParamsT,
    ) -> str:
        """Return the URL template for the given operation.

        Base resources only support ``read`` and ignore subscription/params in the
        template construction. Subclasses should override when they need operation-
        specific templates.

        :param operation: Operation name (e.g. "read").
        :param subscription_id: Subscription identifier.
        :param url_params: URL parameters required by the resource type.
        :return: URL template string.
        """
        if operation != "read":
            raise ValueError(f"Unsupported operation '{operation}' for {cls.__name__}")
        return cls._url_template
    
    @classmethod
    def from_response(
        cls, data_dict: Dict[str, Any], **kwargs: Any
    ) -> "ResourceType":
        """Create instance from API response data and request parameters.

        :param cls: The resource type class
        :type cls: Type[TResourceType]
        :param data_dict: The response data dictionary from Azure API
        :type data_dict: Dict[str, Any]
        :param url_params: URL parameters required by the resource type.
        :type url_params: PathParamsT
        :return: Created instance of the resource type
        :rtype: TResourceType
        """
        properties = data_dict.get('properties', {})

        # Create instance with constructor parameters from kwargs
        instance = cls(**kwargs, properties=properties)

        # Set response data attributes
        instance.id = data_dict.get('id')
        instance.name = data_dict.get('name')
        instance.type = data_dict.get('type')

        return instance

    @classmethod
    def build_instance_path_arguments_from_params(
        cls,
        *,
        subscription_id: str,
        url_params: PathParamsT,
    ) -> Dict[str, Any]:
        """Build path arguments dictionary from URL parameters.

        Base resources only use subscription ID. Subclasses should override when
        they need additional path arguments.

        :param subscription_id: Subscription identifier.
        :param url_params: URL parameters required by the resource type.
        :return: Dictionary of path arguments.
        """
        return {
            "subscriptionId": subscription_id,
        }
