# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import

from ._client import ManagementClient  # type: ignore
from .aio import AsyncManagementClient  # type: ignore
from ._version import VERSION

# Export shared models for convenience
from ._models import (
    ApiKey,
    ApiKeyListResult,
    ConfigurationStore,
    ConfigurationStoreListResult,
    Sku,
    UserIdentity,
    ResourceIdentity,
    KeyVaultProperties,
    EncryptionProperties,
    SystemData,
    PrivateEndpointConnectionReference,
    DataPlaneProxyProperties,
)

__version__ = VERSION


__all__ = [
    "ManagementClient",
    "AsyncManagementClient",
    # Models
    "ApiKey",
    "ApiKeyListResult", 
    "ConfigurationStore",
    "ConfigurationStoreListResult",
    "Sku",
    "UserIdentity",
    "ResourceIdentity", 
    "KeyVaultProperties",
    "EncryptionProperties",
    "SystemData",
    "PrivateEndpointConnectionReference",
    "DataPlaneProxyProperties",
]
