# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, Optional, TYPE_CHECKING, cast, Dict, Type, Literal, Union, overload
from typing_extensions import Self

from azure.core.pipeline import policies
from azure.core.rest import AsyncHttpResponse, HttpRequest
from azure.core.settings import settings
from azure.mgmt.core import AsyncARMPipelineClient
from azure.mgmt.core.policies import AsyncARMAutoResourceProviderRegistrationPolicy
from azure.mgmt.core.tools import get_arm_endpoints

from .._configuration import ManagementClientConfiguration
from ._service_registry.service_factory import AsyncServiceProviderFactory
from ._service_registry.azure_mgmt_appconfiguration import AsyncAppConfigurationFactory

if TYPE_CHECKING:
    from azure.core.credentials_async import AsyncTokenCredential

# Type alias for supported service providers
SupportedProviders = Literal["Microsoft.AppConfiguration"]

AsyncFactoryType = Union[AsyncServiceProviderFactory, AsyncAppConfigurationFactory]


class AsyncManagementClient:  # pylint: disable=client-accepts-api-version-keyword
    """Async Azure Management Client with service provider factory support."""

    # Registry of available service provider factories
    service_factories: Dict[str, Type[AsyncServiceProviderFactory]] = {
        "Microsoft.AppConfiguration": AsyncAppConfigurationFactory,
    }

    def __init__(
        self, credential: "AsyncTokenCredential", subscription_id: str, **kwargs: Any # pylint:disable=client-accepts-api-version-keyword
    ) -> None:
        _cloud = kwargs.pop("cloud_setting", None) or settings.current.azure_cloud  # type: ignore
        _endpoints = get_arm_endpoints(_cloud)
        base_url = _endpoints["resource_manager"]
        credential_scopes = kwargs.pop("credential_scopes", _endpoints["credential_scopes"])
        self._config = ManagementClientConfiguration(
            credential=credential, subscription_id=subscription_id, credential_scopes=credential_scopes, **kwargs
        )

        _policies = kwargs.pop("policies", None)
        if _policies is None:
            _policies = [
                policies.RequestIdPolicy(**kwargs),
                self._config.headers_policy,
                self._config.user_agent_policy,
                self._config.proxy_policy,
                policies.ContentDecodePolicy(**kwargs),
                AsyncARMAutoResourceProviderRegistrationPolicy(),
                self._config.redirect_policy,
                self._config.retry_policy,
                self._config.authentication_policy,
                self._config.custom_hook_policy,
                self._config.logging_policy,
                policies.DistributedTracingPolicy(**kwargs),
                policies.SensitiveHeaderCleanupPolicy(**kwargs) if self._config.redirect_policy else None,
                self._config.http_logging_policy,
            ]
        self._client: AsyncARMPipelineClient = AsyncARMPipelineClient(base_url=cast(str, base_url), policies=_policies, **kwargs)

    @overload
    def __call__(  # pylint: disable=client-method-name-no-double-underscore
        self,
        service_provider: Literal["Microsoft.AppConfiguration"],
        subscription_id: Optional[str] = None,
        api_version: Optional[str] = None
    ) -> AsyncAppConfigurationFactory: ...

    @overload
    def __call__(  # pylint: disable=client-method-name-no-double-underscore
        self,
        service_provider: str,
        subscription_id: Optional[str] = None,
        api_version: Optional[str] = None
    ) -> AsyncServiceProviderFactory: ...

    def __call__(  # pylint: disable=client-method-name-no-double-underscore
        self,
        service_provider: str,
        subscription_id: Optional[str] = None,
        api_version: Optional[str] = None
    ) -> Union[AsyncAppConfigurationFactory, AsyncServiceProviderFactory]:
        """Create an async service client for the specified resource provider.
        
        :param service_provider: The name of the service provider (e.g., 'Microsoft.AppConfiguration')
        :type service_provider: str or SupportedProviders
        :param subscription_id: Optional subscription ID. If not provided, uses client's default.
        :type subscription_id: str
        :param api_version: Optional API version for the service provider. If not provided, uses provider's default.
        :type api_version: str
        :return: An async service client that can perform operations for the specified resource provider
        :rtype: AsyncFactoryType
        
        Example usage:
            client = AsyncManagementClient(credential, subscription_id)
            
            # Get an App Configuration service client with default API version
            app_config = client("Microsoft.AppConfiguration")
            
            # Get an App Configuration service client with specific API version
            app_config = client("Microsoft.AppConfiguration", api_version="2023-03-01")
            
            # List all configuration stores
            response = await app_config.get("configurationStores")
            
            # Get a specific configuration store
            response = await app_config.get("configurationStores/mystore", resource_group="mygroup")
            
            # Create a new configuration store
            store_data = {"location": "eastus", "sku": {"name": "standard"}}
            response = await app_config.put("configurationStores/mystore", model=store_data, resource_group="mygroup")
        """
        # Check if we have a specialized factory for this provider
        try:
            return self.service_factories[service_provider](self, service_provider, subscription_id, api_version)
        except KeyError as e:
            raise ValueError(f"Service provider '{service_provider}' is not supported.") from e

    @classmethod
    def register_service_factory(
        cls,
        service_provider: Union[str, SupportedProviders],
        factory_class: Type[AsyncServiceProviderFactory]
        ) -> None:
        """Register a specialized async service factory for a resource provider.
        
        This is typically used internally to register optimized service clients
        for specific Azure resource providers.
        
        Note: When adding new providers, update the SupportedProviders type alias as well.
        
        :param service_provider: The name of the service provider
        :type service_provider: Union[str, SupportedProviders]
        :param factory_class: The specialized async factory class for the service provider
        :type factory_class: Type[AsyncServiceProviderFactory]
        """
        cls.service_factories[service_provider] = factory_class

    @classmethod
    def get_supported_providers(cls) -> list[str]:
        """Get a list of supported service providers.
        
        :return: List of supported service provider names
        :rtype: list[str]
        """
        return list(cls.service_factories.keys())

    async def _send_request(self, request: HttpRequest, *, stream: bool = False, **kwargs: Any) -> AsyncHttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = await client._send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.AsyncHttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return await self._client.send_request(request_copy, stream=stream, **kwargs)  # type: ignore

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> Self:
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details: Any) -> None:
        await self._client.__aexit__(*exc_details)