# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import json
from copy import deepcopy
from typing import Any, TYPE_CHECKING, TypeVar, Type, List, Optional, Iterator, Mapping, Dict
from collections.abc import MutableMapping

from azure.core.pipeline import policies
from azure.core.rest import HttpRequest, HttpResponse
from azure.core.paging import ItemPaged
from azure.core.exceptions import (
    HttpResponseError,
    ClientAuthenticationError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    map_error,
)
from azure.core.utils import case_insensitive_dict
from azure.core.tracing.decorator import distributed_trace
from azure.mgmt.core import ARMPipelineClient
from azure.mgmt.core.policies import ARMAutoResourceProviderRegistrationPolicy
from azure.mgmt.core.exceptions import ARMErrorFormat

from . import models as _models
from .models import ResourceType
from ._configuration import CrudConfiguration
from ._serialization import Serializer

if TYPE_CHECKING:
    from azure.core.credentials import TokenCredential

_SERIALIZER = Serializer()
_SERIALIZER.client_side_validation = False

PathParamsT = TypeVar("PathParamsT")

class CrudClient:
    """The CRUD Rest API spec.

    :ivar custom_locations: CustomLocationsOperations operations
    :vartype custom_locations: azure.mgmt.extendedlocation.operations.CustomLocationsOperations
    :param credential: Credential needed for the client to connect to Azure. Required.
    :type credential: ~azure.core.credentials.TokenCredential
    :param subscription_id: The ID of the target subscription. Required.
    :type subscription_id: str
    :param base_url: Service URL. Default value is "https://management.azure.com".
    :type base_url: str
    :keyword api_version: Api Version. Default value is "2021-08-15". Note that overriding this
     default value may result in unsupported behavior. 
    :paramtype api_version: str
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no
     Retry-After header is present.
    """

    def __init__(
        self,
        credential: "TokenCredential",
        subscription_id: str,
        base_url: str = "https://management.azure.com",
        **kwargs: Any
    ) -> None:
        self._config = CrudConfiguration(credential=credential, subscription_id=subscription_id, **kwargs)
        _policies = kwargs.pop("policies", None)
        if _policies is None:
            _policies = [
                policies.RequestIdPolicy(**kwargs),
                self._config.headers_policy,
                self._config.user_agent_policy,
                self._config.proxy_policy,
                policies.ContentDecodePolicy(**kwargs),
                ARMAutoResourceProviderRegistrationPolicy(),
                self._config.redirect_policy,
                self._config.retry_policy,
                self._config.authentication_policy,
                self._config.custom_hook_policy,
                self._config.logging_policy,
                policies.DistributedTracingPolicy(**kwargs),
                policies.SensitiveHeaderCleanupPolicy(**kwargs) if self._config.redirect_policy else None,
                self._config.http_logging_policy,
            ]
        self._client: ARMPipelineClient = ARMPipelineClient(base_url=base_url, policies=_policies, **kwargs)


    def _send_request(self, request: HttpRequest, *, stream: bool = False, **kwargs: Any) -> HttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client._send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, stream=stream, **kwargs)  # type: ignore

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> "CrudClient":
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details: Any) -> None:
        self._client.__exit__(*exc_details)

    @distributed_trace
    def read(
        self,
        *,
        resource_type: ResourceType[Any, PathParamsT],
        url_params: PathParamsT,
        **kwargs: Any
    ) -> ResourceType[Any, PathParamsT]:
        """Read a resource of the specified type.

        :param resource_type: The resource type class
        :type resource_type: Type[TResource]
        :keyword url_params: URL parameters required by the resource type.
        :paramtype url_params: PathParamsT
        :return: An instance of the resource type.
        :rtype: TResource
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version = kwargs.pop(
            "api_version", 
            _params.pop("api-version", getattr(resource_type, "api_version"))
        )
        accept = _headers.pop("Accept", "application/json")

        # Let the resource type build its own URL and path arguments
        url_template = resource_type.get_operation_url("read", self._config.subscription_id, url_params)

        path_arguments = resource_type.build_instance_path_arguments_from_params(
            subscription_id=self._config.subscription_id,
            url_params=url_params,
        )

        # Serialize path arguments for URL safety
        serialized_path_args = {}
        for key, value in path_arguments.items():
            serialized_path_args[key] = _SERIALIZER.url(key.lower(), value, "str")

        _url = url_template.format(**serialized_path_args)

        _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str") # pylint: disable=specify-parameter-names-in-call
        _headers["Accept"] = _SERIALIZER.header("accept", accept, "str") # pylint: disable=specify-parameter-names-in-call

        request = HttpRequest("GET", _url, params=_params, headers=_headers)
        response = self._send_request(request, stream=True, **kwargs)

        data = response.read()

        if response.status_code not in [200]:
            raise HttpResponseError(response=response)

        # Parse JSON response to dict
        data_dict = json.loads(data.decode('utf-8'))

        instance = resource_type.from_response(
            data_dict,
            **kwargs,
        )

        return instance
    
    @distributed_trace
    def create(
        self,
        *,
        resource_type: ResourceType[Any, PathParamsT],
        url_params: PathParamsT,
        **kwargs: Any
    ) -> None:
        """Create a resource of the specified type.

        :param resource_type: The resource type class to create
        :type resource_type: Type[TResource]
        :keyword url_params: URL parameters required by the resource type.
        :paramtype url_params: PathParamsT
        :return: An instance of the resource type.
        :rtype: TResource
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version = kwargs.pop(
            "api_version", 
            _params.pop("api-version", getattr(resource_type, "api_version"))
        )
        accept = _headers.pop("Accept", "application/json")
        content_type = _headers.pop("Content-Type", "application/json")

        # Let the resource type build its own URL and path arguments
        url_template = resource_type.get_operation_url("create", self._config.subscription_id, url_params)

        path_arguments = resource_type.build_instance_path_arguments_from_params(
            subscription_id=self._config.subscription_id,
            url_params=url_params,
        )

        # Serialize path arguments for URL safety
        serialized_path_args = {}
        for key, value in path_arguments.items():
            serialized_path_args[key] = _SERIALIZER.url(key.lower(), value, "str")

        _url = url_template.format(**serialized_path_args)

        _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str") # pylint: disable=specify-parameter-names-in-call
        _headers["Accept"] = _SERIALIZER.header("accept", accept, "str") # pylint: disable=specify-parameter-names-in-call
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str") # pylint: disable=specify-parameter-names-in-call

        # Serialize the resource to JSON for the request body
        body_content = json.dumps(resource_type.to_dict())

        request = HttpRequest("PUT", _url, params=_params, headers=_headers, content=body_content)
        response = self._send_request(request, stream=True, **kwargs)

        data = response.read()

        if response.status_code not in [200, 201]:
            raise HttpResponseError(response=response)

        #TODO what exactly do we return on create
        return None

    @distributed_trace
    def delete(  # pylint: disable=inconsistent-return-statements
        self,
        *,
        resource_type: ResourceType[Any, PathParamsT],
        url_params: PathParamsT,
        **kwargs: Any
    ) -> None:
        """Delete a resource of the specified type.

        :param resource_type: The resource type class to delete
        :type resource_type: Type[TResource]
        :keyword url_params: URL parameters required by the resource type.
        :paramtype url_params: PathParamsT
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version = kwargs.pop(
            "api_version", 
            _params.pop("api-version", getattr(resource_type, "api_version"))
        )

        # Let the resource type build its own URL and path arguments
        url_template = resource_type.get_operation_url("delete", self._config.subscription_id, url_params)

        path_arguments = resource_type.build_instance_path_arguments_from_params(
            subscription_id=self._config.subscription_id,
            url_params=url_params,
        )

        # Serialize path arguments for URL safety
        serialized_path_args = {}
        for key, value in path_arguments.items():
            serialized_path_args[key] = _SERIALIZER.url(key.lower(), value, "str")

        _url = url_template.format(**serialized_path_args)

        _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str") # pylint: disable=specify-parameter-names-in-call

        request = HttpRequest("DELETE", _url, params=_params, headers=_headers)
        _stream = False
        response = self._send_request(request, stream=_stream, **kwargs)

        if response.status_code not in [200, 204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response, error_format=ARMErrorFormat)
        
    @distributed_trace
    def update(  # pylint: disable=inconsistent-return-statements
        self,
        *,
        resource_type: ResourceType[Any, PathParamsT],
        url_params: PathParamsT,
        **kwargs: Any
    ) -> ResourceType[Any, PathParamsT]:
        """Update a resource of the specified type.

        :param resource_type: The resource type class to update
        :type resource_type: Type[TResource]
        :keyword url_params: URL parameters required by the resource type.
        :paramtype url_params: PathParamsT
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version = kwargs.pop(
            "api_version", 
            _params.pop("api-version", getattr(resource_type, "api_version"))
        )
        accept = _headers.pop("Accept", "application/json")
        content_type = _headers.pop("Content-Type", "application/json")

        # Let the resource type build its own URL and path arguments
        url_template = resource_type.get_operation_url("update", self._config.subscription_id, url_params)

        path_arguments = resource_type.build_instance_path_arguments_from_params(
            subscription_id=self._config.subscription_id,
            url_params=url_params,
        )

        # Serialize path arguments for URL safety
        serialized_path_args = {}
        for key, value in path_arguments.items():
            serialized_path_args[key] = _SERIALIZER.url(key.lower(), value, "str")

        _url = url_template.format(**serialized_path_args)

        _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str") # pylint: disable=specify-parameter-names-in-call
        _headers["Accept"] = _SERIALIZER.header("accept", accept, "str") # pylint: disable=specify-parameter-names-in-call
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str") # pylint: disable=specify-parameter-names-in-call

        # Serialize the resource to JSON for the request body
        body_content = json.dumps(resource_type.to_dict())

        request = HttpRequest("PATCH", _url, params=_params, headers=_headers, content=body_content)
        response = self._send_request(request, stream=True, **kwargs)

        data = response.read()

        if response.status_code not in [200, 201]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response, error_format=ARMErrorFormat)

        data_dict = json.loads(data.decode('utf-8'))

        instance = resource_type.from_response(
            data_dict,
            **kwargs,
        )

        return instance
    
    @distributed_trace
    def list(
        self,
        *,
        resource_type: ResourceType[Any, PathParamsT],
        url_params: PathParamsT,
        **kwargs: Any
    ) -> ItemPaged[ResourceType[Any, PathParamsT]]:
        """List resources of the specified type.

        :param resource_type: The resource type class
        :type resource_type: Type[TResource]
        :keyword url_params: URL parameters required by the resource type.
        :paramtype url_params: PathParamsT
        :return: An iterator of resource instances.
        :rtype: ItemPaged[TResource]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version = kwargs.pop(
            "api_version", 
            _params.pop("api-version", getattr(resource_type, "api_version"))
        )
        
        # Extract optional list parameters from url_params
        # TypedDict requires explicit handling of optional fields
        maxpagesize = url_params.get("maxpagesize") if isinstance(url_params, dict) else None
        filter_param = url_params.get("filter") if isinstance(url_params, dict) else None
        include = url_params.get("include") if isinstance(url_params, dict) else None
        
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        def prepare_request(next_link=None):
            if not next_link:
                # Let the resource type build its own URL
                url_template = resource_type.get_operation_url("list", self._config.subscription_id, url_params)

                path_arguments = resource_type.build_instance_path_arguments_from_params(
                    subscription_id=self._config.subscription_id,
                    url_params=url_params,
                )

                # Serialize path arguments for URL safety
                serialized_path_args = {}
                for key, value in path_arguments.items():
                    serialized_path_args[key] = _SERIALIZER.url(key.lower(), value, "str")

                _url = url_template.format(**serialized_path_args)
                
                _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
                
                # Add optional query parameters
                if maxpagesize is not None:
                    _params["$maxpagesize"] = _SERIALIZER.query("maxpagesize", maxpagesize, "str")
                if filter_param is not None:
                    _params["$filter"] = _SERIALIZER.query("filter", filter_param, "str")
                if include is not None:
                    _params["$include"] = _SERIALIZER.query("include", include, "str")
                
                _headers["Accept"] = _SERIALIZER.header("accept", "application/json", "str")

                _request = HttpRequest("GET", _url, params=_params, headers=_headers, **kwargs)
                _request.url = self._client.format_url(_request.url)
            else:
                # Handle pagination with next link
                import urllib.parse
                _parsed_next_link = urllib.parse.urlparse(next_link)
                _next_request_params = case_insensitive_dict(
                    {
                        key: [urllib.parse.quote(v) for v in value]
                        for key, value in urllib.parse.parse_qs(_parsed_next_link.query).items()
                    }
                )
                _next_request_params["api-version"] = api_version
                _request = HttpRequest(
                    "GET", urllib.parse.urljoin(next_link, _parsed_next_link.path), params=_next_request_params
                )
                _request.url = self._client.format_url(_request.url)
                _request.method = "GET"
            
            return _request

        def extract_data(pipeline_response):
            # Parse the response
            data = json.loads(pipeline_response.http_response.read().decode('utf-8'))
            
            # Extract the list of items and next link
            list_of_items = data.get("value", [])
            
            # Convert each item dict to resource type instance
            deserialized_items = []
            for item_dict in list_of_items:
                instance = resource_type.from_response(item_dict, **kwargs)
                deserialized_items.append(instance)
            
            next_link = data.get("nextLink") or None
            return next_link, iter(deserialized_items)

        def get_next(next_link=None):
            _request = prepare_request(next_link)
            _stream = False
            pipeline_response = self._client._pipeline.run(_request, stream=_stream, **kwargs)
            response = pipeline_response.http_response

            if response.status_code not in [200]:
                map_error(status_code=response.status_code, response=response, error_map=error_map)
                raise HttpResponseError(response=response, error_format=ARMErrorFormat)

            return pipeline_response

        return ItemPaged(get_next, extract_data)
    
    @distributed_trace
    def action(
        self,
        *,
        resource_type: ResourceType[Any, PathParamsT],
        action_name: str,
        url_params: PathParamsT,
        body: Optional[Dict[str, Any]] = None,
        **kwargs: Any
    ) -> Any:
        """Perform an action (POST operation) on a resource.

        :param resource_type: The resource type class
        :type resource_type: Type[TResource]
        :param action_name: The name of the action to perform (e.g., 'setLegalHold', 'lease')
        :type action_name: str
        :keyword url_params: URL parameters required by the resource type.
        :paramtype url_params: PathParamsT
        :keyword body: Optional request body for the action.
        :paramtype body: Dict[str, Any]
        :return: The action response or None
        :rtype: Any
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version = kwargs.pop(
            "api_version", 
            _params.pop("api-version", getattr(resource_type, "api_version"))
        )
        accept = _headers.pop("Accept", "application/json")
        
        # Get the action URL from the resource type
        url_template = resource_type.get_action_url(action_name, self._config.subscription_id, url_params)

        path_arguments = resource_type.build_instance_path_arguments_from_params(
            subscription_id=self._config.subscription_id,
            url_params=url_params,
        )

        # Serialize path arguments for URL safety
        serialized_path_args = {}
        for key, value in path_arguments.items():
            serialized_path_args[key] = _SERIALIZER.url(key.lower(), value, "str")

        _url = url_template.format(**serialized_path_args)

        _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
        _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

        # Prepare request body if provided
        body_content = None
        if body is not None:
            _headers["Content-Type"] = _SERIALIZER.header("content_type", "application/json", "str")
            body_content = json.dumps(body)

        request = HttpRequest("POST", _url, params=_params, headers=_headers, content=body_content)
        response = self._send_request(request, stream=True, **kwargs)

        data = response.read()

        if response.status_code not in [200, 202]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response, error_format=ARMErrorFormat)

        # Parse response if there's content
        if data:
            data_dict = json.loads(data.decode('utf-8'))
            return data_dict
        
        return None
